import { describe, it, expect } from 'vitest';
import { defineShape, timeParams, evalAt, computeMove, stopDistance, stopTime, commitStopDist } from '../src/engine/MotionProfile';
import VECTORS from './golden_vectors.json';

/**
 * PARITY WITH Lehel4321/MotionProfileSolver
 *
 * golden_vectors.json is copied VERBATIM from the MotionProfileSolver
 * repository (generated by its Python reference engine, motion_engine.py).
 * Running the rotary knife's MotionProfile.ts against the same vectors
 * proves the feed axis here runs on EXACTLY the same S-curve math as the
 * original solver — if either side ever drifts, this file fails.
 */

const RTOL = 1e-9;
const close = (a: number, b: number, rtol = RTOL) =>
  Math.abs(a - b) <= Math.max(rtol * Math.max(Math.abs(a), Math.abs(b)), 1e-9);

describe('MotionProfileSolver golden-vector parity', () => {
  for (const c of (VECTORS as any).cases as any[]) {
    it(c.name, () => {
      const i = c.inputs, exp = c.expected;
      const { sh, va, sa, sv } = defineShape(i.amax, i.jmax, i.vmax, i.s);
      expect(sh).toBe(exp.shape);
      expect(close(va, exp.va)).toBe(true);
      expect(close(sa, exp.sa)).toBe(true);
      expect(close(sv, exp.sv)).toBe(true);

      const tp = timeParams(i.vmax, i.amax, i.jmax, i.s, sh!);
      expect(tp).not.toBeNull();
      expect(close(tp!.t7, exp.t7)).toBe(true);

      for (const smp of c.samples) {
        const [j, a, v, p] = evalAt(i.jmax, tp!, smp.t);
        expect(close(j, smp.jerk), `jerk at t=${smp.t}`).toBe(true);
        expect(close(a, smp.accel), `accel at t=${smp.t}`).toBe(true);
        expect(close(v, smp.vel), `vel at t=${smp.t}`).toBe(true);
        expect(close(p, smp.pos), `pos at t=${smp.t}`).toBe(true);
      }
    });
  }
});

/**
 * Physical-invariant sweep, mirroring MotionProfileSolver's
 * test_invariants: 8⁴ = 4096 parameter combinations. Every profile must
 * end at the requested distance at rest and never exceed vmax or amax.
 */
describe('S-curve invariants (4096-combination sweep, as in MotionProfileSolver)', () => {
  const SWEEP = [0.001, 0.1, 1, 5, 20, 100, 1000, 5000];

  it('every profile closes at distance s at rest, within limits', () => {
    for (const s of SWEEP) for (const vmax of SWEEP) for (const amax of SWEEP) for (const jmax of SWEEP) {
      const { sh } = defineShape(amax, jmax, vmax, s);
      expect(sh, `no shape for s=${s} v=${vmax} a=${amax} j=${jmax}`).not.toBeNull();
      const tp = timeParams(vmax, amax, jmax, s, sh!)!;
      expect(tp.t7 > 0 && Number.isFinite(tp.t7)).toBe(true);

      const [, aEnd, vEnd, pEnd] = evalAt(jmax, tp, tp.t7);
      expect(Math.abs(pEnd - s) / s).toBeLessThan(1e-6);
      expect(Math.abs(vEnd) / vmax).toBeLessThan(1e-2);
      expect(Math.abs(aEnd) / amax).toBeLessThan(1e-4);

      for (let k = 0; k <= 20; k++) {
        const [, a, v] = evalAt(jmax, tp, (tp.t7 * k) / 20);
        expect(v).toBeLessThanOrEqual(vmax * (1 + 1e-9));
        expect(Math.abs(a)).toBeLessThanOrEqual(amax * (1 + 1e-5));
      }
    }
  });
});

/**
 * The braking formulas the rotary knife adds on top (used for the
 * graceful stop to the knife park phase) must agree with the 7-phase
 * evaluator itself: braking from v to standstill is by symmetry exactly
 * half of the solver's sv round trip (accelerate 0→v, decelerate v→0).
 */
describe('braking math consistency with the 7-phase profile', () => {
  const cases: [number, number, number][] = [
    [1000, 30000, 300000], [500, 30000, 300000], [2500, 30000, 300000],
    [1000, 2000, 20000], [100, 500, 5000], [3000, 30000, 3000000],
  ];
  for (const [v, A, J] of cases) {
    it(`stopDistance/stopTime(v=${v}, A=${A}, J=${J}) match the profile`, () => {
      const { sv } = defineShape(A, J, v, Number.MAX_SAFE_INTEGER / 1e6);
      expect(close(stopDistance(v, A, J), sv / 2, 1e-9)).toBe(true);

      // stopTime equals the accel-phase duration t3 of a cruise profile
      const mv = computeMove(sv * 2, v, A, J)!;
      expect(close(stopTime(v, A, J), mv.tp.t3, 1e-9)).toBe(true);

      // commitStopDist from steady cruise (a = 0) equals stopDistance
      expect(close(commitStopDist(v, 0, A, J), stopDistance(v, A, J))).toBe(true);
    });
  }
});
